### ISSUE TITLE
我想把solo部署到GAE上，但是它报了一个错

### ISSUE THREAD

**Issue by cjahv** [b3log/solo#12227]
```
[INFO] java.lang.IllegalStateException: Unable to locate the default servlet for serving static content. Please report this bug on https://github.com/b3log/b3log-latke/issues/new
[INFO] 	at org.b3log.latke.servlet.handler.StaticResourceHandler.<init>(StaticResourceHandler.java:95)
[INFO] 	at org.b3log.latke.servlet.DispatcherServlet.init(DispatcherServlet.java:66)
[INFO] 	at javax.servlet.GenericServlet.init(GenericServlet.java:212)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
[INFO] 	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
[INFO] 	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
[INFO] 	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
[INFO] 	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
[INFO] 	at org.mortbay.jetty.Server.doStart(Server.java:224)
[INFO] 	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
[INFO] 	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:268)
[INFO] 	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
[INFO] 	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
[INFO] 	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
[INFO] 	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
[INFO] 	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:252)
[INFO] 	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:54)
[INFO] 	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:218)
[INFO] 	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:216)
[INFO] 	at java.security.AccessController.doPrivileged(Native Method)
[INFO] 	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:216)
[INFO] 	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:129)
[INFO] 	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:82)
[INFO] 	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
[INFO] 	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:66)
[INFO] 	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:44)
```

**Comment by 88250** [comment]
现在的版本不支持部署 GAE 了。

**Comment by cjahv** [comment]
哦豁
