### ISSUE TITLE
解压之后运行命令报404,请问这是为什么呢?

### ISSUE THREAD

**Issue by ljf1172361058** [b3log/solo#12236]
HTTP ERROR 404

Problem accessing /error/404.html. Reason:

    Not Found
Powered by Jetty://

**Comment by 88250** [comment]
请看下日志是否有异常信息输出。

**Comment by ljf1172361058** [comment]
1.7 
ERROR]-[2017-01-13 22:47:18]-[org.b3log.latke.servlet.HttpControl:96]: Request processing failed
java.lang.IllegalStateException: Not found static resources definition from [static-resources.xml]
	at org.b3log.latke.util.StaticResources.init(StaticResources.java:102)
	at org.b3log.latke.util.StaticResources.isStatic(StaticResources.java:76)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:108)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:94)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
	at org.eclipse.jetty.server.Dispatcher.error(Dispatcher.java:77)

**Comment by 88250** [comment]
看下 WEB-INF/static-resources.xml 这个文件内容是否正常。另外，你是自己打包的还是下载的？

**Comment by ljf1172361058** [comment]
我从网盘上下载的 然后直接解压运行文档中的命令

**Comment by 88250** [comment]
路径里面不要有中文，比如你放到 D:\ 下面试试

**Comment by ljf1172361058** [comment]
谢谢了,路径里面没有中午就行了,多谢 @88250

**Comment by 88250** [comment]
客气，这个问题也是程序不完善导致，后续我看下是否能够解决 :)

**Comment by ljf1172361058** [comment]
@88250  那真是辛苦你了
