### ISSUE TITLE
请问这是什么问题？

### ISSUE THREAD

**Issue by beckno9** [b3log/solo#12252]
```
[ERROR]-[2017-03-05 14:26:58]-[org.b3log.solo.Starter:172]: Server start failed
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:366)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.b3log.solo.Starter.main(Starter.java:170)
```
我从控制台输出看到了这些错误，我配置了MySQL数据库，那么具体怎么安装？

### 补充 ###
服务器: CentOS 6.*  
Nginx + Tomcat 8.* + JDK 1.8 +PHP 7 + MariaDB 10.1

**Comment by 88250** [comment]
8080 端口是不是被占用了？
