### ISSUE TITLE
验证码图片不显示

### ISSUE THREAD

**Issue by lyulianghui** [b3log/solo#12254]
验证码不出来，后台报错
 java.lang.NullPointerException
        at org.b3log.latke.servlet.renderer.PNGRenderer.render(PNGRenderer.java:65)
        at org.b3log.latke.servlet.DispatcherServlet.result(DispatcherServlet.java:111)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:89)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:91)

**Comment by lyulianghui** [comment]
1.9.0版本

**Comment by lyulianghui** [comment]
权限问题导致的，close
