### ISSUE TITLE
在安装后并执行了windows命令，绑定端口9090，出现错误。

### ISSUE THREAD

**Issue by zhangqingyun123** [b3log/solo#12269]
[ERROR]-[2017-04-18 10:33:16]-[org.b3log.latke.servlet.HttpControl:104]: Request [
    method=GET,
    URL=http://localhost:9090/favicon.ico,
    contentType=null,
    characterEncoding=UTF-8,
    local=[
        addr=0:0:0:0:0:0:0:1,
        port=9090,
        name=0:0:0:0:0:0:0:1],
    remote=[
        addr=0:0:0:0:0:0:0:1,
        port=51176,
        host=0:0:0:0:0:0:0:1],
    headers=[
        Cookie=JSESSIONID=tiae3xsax2hb16z28xbp6j9y7
        Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
        Connection=keep-alive
        Host=localhost:9090
        Accept-Language=zh-CN,zh;q=0.8,en;q=0.5,en-US;q=0.3
        Accept-Encoding=gzip, deflate
    ]
] processing failed 
java.lang.IllegalStateException: Not found static resources definition from [static-resources.xml]
	at org.b3log.latke.util.StaticResources.init(StaticResources.java:102)
	at org.b3log.latke.util.StaticResources.isStatic(StaticResources.java:76)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:108)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:115)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)

**Comment by zhangqingyun123** [comment]
@88250 windows命令执行成功，但是log报出找不到文件，可以帮忙看看吗？

**Comment by 88250** [comment]
解压路径没有空格吧？

**Comment by zhangqingyun123** [comment]
什么意思？  我直接将war包解压，然后进入到这个目录D:\b3log-solo\solo-2.0.0，之后执行java -cp WEB-INF/lib/*;WEB-INF/classes org.b3log.solo.Starter -lp 9090 -sp 9090

**Comment by zhangqingyun123** [comment]
@88250 解压和启动都成功了，只是在访问http://localhost:9090的时候报错了

**Comment by 88250** [comment]
今晚我看一下，谢谢反馈先。

**Comment by 88250** [comment]
好奇怪，我这里试了下是好的啊：

![image](https://cloud.githubusercontent.com/assets/873584/25132057/b70ab344-247a-11e7-9345-4b49be78343c.png)

**Comment by 88250** [comment]
我先关闭这个 issue 了，有情况直接回复就好。
