### ISSUE TITLE
尝试在Glassfish 4上部署时发生 Unsatisfied dependencies for type ...异常，tomcat成功

### ISSUE THREAD

**Issue by jasonthinks** [b3log/solo#12260]
Exception 31 :

org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type LangPropsService with qualifiers @Default

  at injection point [BackedAnnotatedField] @Inject private org.b3log.solo.processor.LoginProcessor.langPropsService

  at org.b3log.solo.processor.LoginProcessor.langPropsService(LoginProcessor.java:0)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:355)

	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:277)

	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:130)

	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:151)

	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:494)

	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:480)

	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:455)

	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:454)

	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)

	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:226)

	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)

	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:329)

	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)

	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:220)

	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:487)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)

	at java.security.AccessController.doPrivileged(Native Method)

	at javax.security.auth.Subject.doAs(Subject.java:360)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)

	at java.security.AccessController.doPrivileged(Native Method)

	at javax.security.auth.Subject.doAs(Subject.java:360)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)

	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)

	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:263)

	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:234)

	at org.glassfish.admin.rest.utils.ResourceUtil.runCommand(ResourceUtil.java:285)

	at org.glassfish.admin.rest.resources.TemplateListOfResource.createResource(TemplateListOfResource.java:136)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)

	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)

	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)

	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)

	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)

	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)

	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)

	at org.glassfish.admin.rest.adapter.RestAdapter$2.service(RestAdapter.java:316)

	at org.glassfish.admin.rest.adapter.RestAdapter.service(RestAdapter.java:179)

	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)

	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)

	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)

	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)

	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)

	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)

	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)

	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)

	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)

	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)

	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)

	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)

	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)

	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)

	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)

	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)

	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)

	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)

	at java.lang.Thread.run(Thread.java:745)

. Please see server.log for more details.]]

**Comment by 88250** [comment]
应该是需要禁用一下容器自带的依赖注入，可能需要查一下 weld 相关文档了。
