### ISSUE TITLE
配置 MetaWeblog API 报错

### ISSUE THREAD

**Issue by peng051410** [b3log/solo#12308]
我在配置metawebblog api时，出现如下错误：
![image](https://user-images.githubusercontent.com/5512326/26913268-55cd9656-4c4c-11e7-816b-670506bd5d58.png)
我的配置如下：
![image](https://user-images.githubusercontent.com/5512326/26913298-778fb152-4c4c-11e7-8a11-3856faebc6f0.png)

请求是哪里的配置不对？谢谢

**Comment by 88250** [comment]
有可能是 bug，能帮忙贴一下报错部分的日志么。

**Comment by peng051410** [comment]
@88250 我在后台看到的日志如下：
`[INFO ]-[2017-06-08 13:54:18]-[org.b3log.solo.api.metaweblog.MetaWeblogAPI:221]: MetaWeblog[methodName=blogger.getUsersBlogs]
[ERROR]-[2017-06-08 13:54:18]-[org.b3log.solo.api.metaweblog.MetaWeblogAPI:293]: JSONObject["oId"] not found.
org.json.JSONException: JSONObject["oId"] not found.
        at org.json.JSONObject.get(JSONObject.java:540)
        at org.json.JSONObject.getString(JSONObject.java:700)
        at org.b3log.solo.api.metaweblog.MetaWeblogAPI.buildBlogInfo(MetaWeblogAPI.java:627)
        at org.b3log.solo.api.metaweblog.MetaWeblogAPI.getUsersBlogs(MetaWeblogAPI.java:483)
        at org.b3log.solo.api.metaweblog.MetaWeblogAPI.metaWeblog(MetaWeblogAPI.java:243)
        at org.b3log.solo.api.metaweblog.MetaWeblogAPI_$$_jvst77e_2b._d5metaWeblog(MetaWeblogAPI_$$_jvst77e_2b.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:101)
        at org.b3log.solo.api.metaweblog.MetaWeblogAPI_$$_jvst77e_2b.metaWeblog(MetaWeblogAPI_$$_jvst77e_2b.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvokeHandler.java:58)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.java:108)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:60)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(RequestDispatchHandler.java:92)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestPrepareHandler.java:45)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:119)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:84)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:87)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:92)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
`
看情况应该是json哪里没有对应上

**Comment by 88250** [comment]
好的，晚上仔细看下，谢谢。

**Comment by 88250** [comment]
应该修复了，代码已经提交，可以的话请帮忙验证一下，谢谢。
