### ISSUE TITLE
抛异常,看是不是有bug

### ISSUE THREAD

**Issue by BianJian** [b3log/solo#12311]
```
[ERROR]-[2017-06-12 17:56:23]-[org.b3log.latke.servlet.HttpControl:104]: Request
 [
    method=GET,
    URL=http://www.xxxxx.com/tag-articles-feed.do,
    contentType=null,
    characterEncoding=UTF-8,
    local=[
        addr=192.168.3.7,
        port=80,
        name=192.168.3.7],
    remote=[
        addr=119.28.78.252,
        port=54352,
        host=192.168.3.7],
    headers=[
        Accept=text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
        User-Agent=Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.11 (KHTML, like
Gecko) Chrome/17.0.963.84 Safari/535.11 SE 2.X MetaSr 1.0
        Connection=keep-alive
        X-Forwarded-For=119.28.78.252, 112.175.238.117
        Host=www.xxxx.com
        X-Real-IP=119.28.78.252
        ProxyAgent=oray phfw
    ]
] processing failed
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvo
keHandler.java:58)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.ja
va:108)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:6
0)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(Request
DispatchHandler.java:92)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestP
repareHandler.java:45)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticRe
sourceHandler.java:119)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.j
ava:84)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800
)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1669)
        at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:8
7)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1652)
        at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:9
2)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1652)
        at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter
.java:71)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.jav
a:245)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java
:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.b3log.solo.processor.FeedProcessor.tagArticlesAtom(FeedProcessor.
java:228)
        at org.b3log.solo.processor.FeedProcessor_$$_jvst886_31._d9tagArticlesAt
om(FeedProcessor_$$_jvst886_31.java)
        at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMetho
dHandler.java:101)
        at org.b3log.solo.processor.FeedProcessor_$$_jvst886_31.tagArticlesAtom(
FeedProcessor_$$_jvst886_31.java)
        ... 42 more
[WARN ]-[2017-06-12 17:56:23]-[org.eclipse.jetty.servlet.ServletHandler:628]: /t
ag-articles-feed.do
java.lang.NullPointerException
        at java.io.PrintWriter.write(PrintWriter.java:473)
        at org.b3log.latke.servlet.renderer.AtomRenderer.render(AtomRenderer.jav
a:65)
        at org.b3log.latke.servlet.DispatcherServlet.result(DispatcherServlet.ja
va:111)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.j
ava:89)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800
)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1669)
        at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:8
7)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1652)
        at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:9
2)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1652)
        at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter
.java:71)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(Servlet
Handler.java:1652)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java
:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.jav
a:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandl
er.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandl
er.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:
515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandle
r.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandle
r.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.j
ava:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.jav
a:245)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java
:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by 88250** [comment]
已经修复，谢谢反馈 👍
