### ISSUE TITLE
删除文章后分类报错

### ISSUE THREAD

**Issue by xinzhongtianxia** [b3log/solo#12338]
1, 正常写一堆博客，关联到某个分类，比如“leetcode”
2. 删除该分类下所有博客
3. 主页点击该分类
4. 500 internal error

**Comment by 88250** [comment]
按理来说删除引用的文章后应该就不会出现标签了。麻烦贴一下报错日志。

**Comment by xinzhongtianxia** [comment]
不是标签，是文章分类。
删除文章后，标签也就不出现了，这时候如果某个分类下面只有这一个已经不出现了的标签，点击时就会报错。


下面是日志：

`[ERROR]-[2017-08-21 09:10:14]-[org.b3log.latke.servlet.HttpControl:104]: Request [
    method=GET,
    URL=http://172.17.0.1:8080/category/test,
    contentType=null,
    characterEncoding=UTF-8,
    local=[
        addr=172.17.0.4,
        port=8080,
        name=172.17.0.4],
    remote=[
        addr=172.17.0.1,
        port=38046,
        host=172.17.0.1],
    headers=[
        Cookie=JSESSIONID=urmeqga8kau4tlie5rmdx6f6; visited="[\"/\",\"/category/Java\",\"/category/MySQL\",\"/category/%E5%BE%AE%E6%9C%8D%E5%8A%A1\",\"/category/test\"]"; b3log-latke="{\"userPassword\":\"7b2401b0b0bb061e9a2eeecc523df6ba\",\"userEmail\":\"453935989@qq.com\"}"; Hm_lvt_ed135bf02c952dddf708c7e432bdc472=1503305931; Hm_lpvt_ed135bf02c952dddf708c7e432bdc472=1503306576
        Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
        Upgrade-Insecure-Requests=1
        Connection=close
        User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
        Referer=http://blog.lanjingdejia.com/
        Host=172.17.0.1:8080
        Accept-Encoding=gzip, deflate
        Accept-Language=zh-CN,zh;q=0.8
        Proxy-Connection=keep-alive
    ]
] processing failed 
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor162.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvokeHandler.java:58)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.java:108)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:60)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(RequestDispatchHandler.java:92)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestPrepareHandler.java:45)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:119)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:87)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:92)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at org.b3log.solo.processor.CategoryProcessor.showCategoryArticles(CategoryProcessor.java:202)
	at org.b3log.solo.processor.CategoryProcessor_$$_jvst448_17._d7showCategoryArticles(CategoryProcessor_$$_jvst448_17.java)
	at sun.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:101)
	at org.b3log.solo.processor.CategoryProcessor_$$_jvst448_17.showCategoryArticles(CategoryProcessor_$$_jvst448_17.java)
	... 42 more
[ERROR]-[2017-08-21 09:10:14]-[org.b3log.latke.servlet.renderer.freemarker.AbstractFreeMarkerRenderer:137]: FreeMarker renders error
FreeMarker template error:
The following has evaluated to null or missing:
==> blogTitle  [in template "category-articles.ftl" at line 5, column 53]
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----
----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${blogTitle}  [in template "category-articles.ftl" at line 5, column 51]
	- Reached through: @head title="${category.categoryTitle...  [in template "category-articles.ftl" at line 5, column 9]
----
Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
	at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:355)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:41)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.renderElementToString(Environment.java:2196)
	at freemarker.core.StringLiteral.evalAndCoerceToString(StringLiteral.java:96)
	at freemarker.core.StringLiteral._eval(StringLiteral.java:73)
	at freemarker.core.Expression.eval(Expression.java:78)
	at freemarker.core.Environment.setMacroContextLocalsFromArguments(Environment.java:739)
	at freemarker.core.Environment.invoke(Environment.java:689)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.MixedContent.accept(MixedContent.java:54)
	at freemarker.core.Environment.visit(Environment.java:324)
	at freemarker.core.Environment.process(Environment.java:302)
	at freemarker.template.Template.process(Template.java:325)
	at org.b3log.latke.servlet.renderer.freemarker.AbstractFreeMarkerRenderer.genHTML(AbstractFreeMarkerRenderer.java:161)
	at org.b3log.latke.servlet.renderer.freemarker.AbstractFreeMarkerRenderer.render(AbstractFreeMarkerRenderer.java:132)
	at org.b3log.latke.servlet.DispatcherServlet.result(DispatcherServlet.java:111)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:87)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:92)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by 88250** [comment]
谢谢反馈，等有空就修复 😅
