### ISSUE TITLE
发布文章错误

### ISSUE THREAD

**Issue by ZHI16** [b3log/solo#12359]
在文章中写<>标签后台会解析JSON错误，报`java.lang.NullPointerException`

**Comment by 88250** [comment]
麻烦发一下日志，谢谢。

**Comment by ZHI16** [comment]
```
[ERROR]-[2017-10-18 15:29:38]-[org.b3log.latke.servlet.HttpControl:104]: Request [
    method=POST,
    URL=http://www.nomoresay.com/console/article/,
    contentType=application/x-www-form-urlencoded; charset=UTF-8,
    characterEncoding=UTF-8,
    local=[
        addr=127.0.0.1,
        port=8080,
        name=localhost],
    remote=[
        addr=211.157.161.98,
        port=33452,
        host=127.0.0.1],
    headers=[
        host=www.nomoresay.com:80
        x-real-ip=211.157.161.98
        connection=close
        content-length=10753
        pragma=no-cache
        cache-control=no-cache
        accept=*/*
        origin=http://www.nomoresay.com
        x-requested-with=XMLHttpRequest
        user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
        content-type=application/x-www-form-urlencoded; charset=UTF-8
        referer=http://www.nomoresay.com/admin-index.do
        accept-encoding=gzip, deflate
        accept-language=zh-CN,zh;q=0.8
        cookie=visited=%5B%22%2Fcategory%2Freading%22%2C%22%2Fabout%22%2C%22%2F%22%2C%22%2Fdynamic.html%22%2C%22%2Ftags.html%22%2C%22%2Farchives.html%22%2C%22%2Flinks.html%22%2C%22%2Farticles%2F2017%2F10%2F17%2F1508227509634.html%22%2C%22%2Farticles%2F2017%2F10%2F17%2F1508228224789.html%22%5D; JSESSIONID=268DBD648E6E01FFE505FB2A56DE234E; skin=; solo=732e32b4c3cbba398e9012784ab5b73ca0e2a4a342dd6dc771f643e2d5d6a4d503c5ba5ec55b3987e36741099b365834b3ded7e1af5d41ad71000314058d99b2428694853f28611635bf9863e0241565aaa3a5d242b89939c00ccd86e6b24dcc0a021f52b034e737e1063ef5e90f6e9c74f493db0d0e644c04ea5a11d1ad5bca977800a26466439eb815deccf404241f92922d1d81b7b7175bf04eb44fce1c948a3ae56da918e1492ffa8756ffb98bcc
    ]
] processing failed 
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvokeHandler.java:58)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.java:108)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:60)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(RequestDispatchHandler.java:92)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestPrepareHandler.java:45)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:119)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:84)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:87)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:92)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.json.JSONException: JSONObject["article"] not found.
        at org.json.JSONObject.get(JSONObject.java:540)
        at org.json.JSONObject.getJSONObject(JSONObject.java:623)
        at org.b3log.solo.processor.console.ArticleConsole.addArticle(ArticleConsole.java:663)
        at org.b3log.solo.processor.console.ArticleConsole_$$_jvst1ae_34._d0addArticle(ArticleConsole_$$_jvst1ae_34.java)
        at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
        at org.b3log.solo.processor.console.ArticleConsole_$$_jvst1ae_34.addArticle(ArticleConsole_$$_jvst1ae_34.java)
        ... 48 more
[ERROR]-[2017-10-18 15:29:38]-[org.b3log.latke.servlet.renderer.JSONRenderer:153]: FreeMarker renders error
java.lang.NullPointerException
        at org.b3log.latke.servlet.renderer.JSONRenderer.render(JSONRenderer.java:141)
        at org.b3log.latke.servlet.DispatcherServlet.result(DispatcherServlet.java:111)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:89)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:87)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:92)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
[ERROR]-[2017-10-18 15:30:24]-[org.b3log.latke.util.Requests:499]: Can not parse request[requestURI=/console/article/, method=POST], returns an empty json object
org.json.JSONException: Expected a ',' or '}' at character 5074
        at org.json.JSONTokener.syntaxError(JSONTokener.java:420)
        at org.json.JSONObject.<init>(JSONObject.java:246)
        at org.json.JSONTokener.nextValue(JSONTokener.java:351)
        at org.json.JSONObject.<init>(JSONObject.java:227)
        at org.json.JSONObject.<init>(JSONObject.java:444)
        at org.b3log.latke.util.Requests.parseRequestJSONObject(Requests.java:497)
        at org.b3log.solo.processor.console.ArticleConsole.addArticle(ArticleConsole.java:659)
        at org.b3log.solo.processor.console.ArticleConsole_$$_jvst1ae_34._d0addArticle(ArticleConsole_$$_jvst1ae_34.java)
        at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
        at org.b3log.solo.processor.console.ArticleConsole_$$_jvst1ae_34.addArticle(ArticleConsole_$$_jvst1ae_34.java)
        at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvokeHandler.java:58)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.java:108)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:60)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(RequestDispatchHandler.java:92)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestPrepareHandler.java:45)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:119)
        at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:84)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:87)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:92)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by 88250** [comment]
你自己修改过代码吗？

**Comment by ZHI16** [comment]
@88250 
没有，war直接放在Web容器下运行的

**Comment by 88250** [comment]
咦，版本是 2.4.0 吗？

**Comment by ZHI16** [comment]
是的 solo-2.4.0.war

**Comment by 88250** [comment]
我刚刚试了下，正文里面带 `<h2>test</h2>` 是 OK 的，你能贴一下你的正文么，我这里尝试重现一下。

**Comment by ZHI16** [comment]
<pre>
长时间使用Eclipse或者MyEclipse慢慢的就会发现越来越蛋疼。过于简单粗暴的界面，过多而无用的插件……废话不多说，进入正题。

* * *

&gt; 首先需要明确一个问题：在传统的Eclipse中的workspace和project相信大家都有一定的了解。但是在Idea中没有了workspace，转而出现了project和module。相信聪明的观众老爷，能猜出来。没错，在Idea中project就相当于Eclipse中的workspace，module就相当于Eclipse中的project。

## 环境说明

笔者使用的IntelliJ IDEA版本是：2017.2.4

## 导入项目

### 在Idea中建立一个空的project（相当于在Eclipse中建立了一个workspace）

1.  File -&gt; New -&gt; Project -&gt; Empty Project，然后选择下一步
2.  输入Project的名字，并选择Project的位置，然后点击Finish
3.  会弹窗提示在新窗口打开还是在当前窗口打开，这里随意选择。笔者选择在当前窗口打开。

![](http://img.blog.csdn.net/20170921162413553?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

### 配置环境JDK

*   打开项目结构 快捷键：`Ctrl + Shift + Alt + S`
*   选择Project
*   在Project SDK 选择New， 选一个本地的JDK_HOME 目录

![](http://img.blog.csdn.net/20170921171637386?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

### 导入传统结构的项目

*   打开项目结构 快捷键：`Ctrl + Shift + Alt + S`

![](http://img.blog.csdn.net/20170921170313663?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

*   导入Eclipse建立的Web项目
*   选择Modules，点击`+` ，我们这里是导入项目所以选择 `Import Module` ，如果需要新建一个项目可以选择`New Module`
*   选择项目所在磁盘的路径， 因为项目是Eclipse创建的，所以我们选择Eclipse这个选项， 一路 Next，最后一步选中我们导入的项目，Finish 完成。
*   导入一个项目之后会默认选择这个模块， 例如本例子中的`Hello` （如果没有可以打开项目结构窗口，选择Modules中的Hello模块即可）, 在这个模块中有几个选项卡，Sources， Paths， Dependencies 这几个。

![](http://img.blog.csdn.net/20170921171937515?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

*   Sources 选项卡， 我们可以看到`Hello` 模块的项目结构，在这里我们可以设置哪一个是源码文件，哪一个是资源文件夹，测试源码， 测试资源文件等。

![](http://img.blog.csdn.net/20170921173524042?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

*   Paths 选择模块的输出路径

![](http://img.blog.csdn.net/20170921173726076?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

*   Dependencies 这里配置模块的依赖关系， 配置jdk，删除不需要的依赖关系

![](http://img.blog.csdn.net/20170921173913195?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

### 导入Maven项目

*   和导入传统项目类似，唯一不同的是 要选择Maven选项，而不是Eclipse。**在导入时，要选择pom.xml文件的上级目录，这一点有别于eclipse**

![](http://img.blog.csdn.net/20170921174942277?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

## 部署项目到Tomcat

### 配置tomcat

*   点击工具栏的设置按钮 -&gt; Edit configurations

![](http://img.blog.csdn.net/20170922110120007?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

![](http://img.blog.csdn.net/20170922110322790?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

*   Name 给tomcat配置一个名字
*   Application server 右侧 Configure 配置tomcat所有目录
*   Open browser 启动项目后使用哪一个浏览器打开，并且配置一个访问的url，
*   VM options 配置jvm参数，如果项目启动报内存溢出，可以在这里更改
*   JRE tomcat 使用的jdk
*   Tomcat Server Settings 配置tomcat端口

现在tomcat中还没有部署任何 artifact 。接下来我们来建立artifact

### 配置artifact

现在工程中只有两个模块，一个是从eclipse中导入的项目（Hello），另一个是导入的Maven项目（comtest）项目项目结构窗口中选择Artifacts可以看到可以部署到tomcat中的artifact。

![](http://img.blog.csdn.net/20170922111457765?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)
![](http://img.blog.csdn.net/20170922111517136?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

我们可以看到Artifacts中只有Maven的项目并没有Eclipse导入的项目？我们要部署那个没有的项目怎么办呢？ 因为Eclipse导入的项目没有添加web模块到项目中，如果Maven工程pom文件没有把打包方式设置成`war` 在Artifacts 中也会没有。

![](http://img.blog.csdn.net/20170922112017294?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

接下来我们添加给Hello模块添加web。

![](http://img.blog.csdn.net/20170922112448333?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

注意添加完Web后会出现两个路径要根据自己项目的实际情况来更改。**在Eclipse中默认的Deployment Root 的名字是WebRoot， 而在idea中名字叫web。**

![](http://img.blog.csdn.net/20170922112952571?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

我们对应修改就行了。因为本例子中Hello项目是Eclipse中的导入的，我们要改成WebRoot。

![](http://img.blog.csdn.net/20170922113520917?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

修改完路径，我们可以直接添加到artifact，Fix -&gt; Create Artifact 就可以了。

![](http://img.blog.csdn.net/20170922113732109?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

也可以在Artifacts 窗口添加，都是可以的

![](http://img.blog.csdn.net/20170922114126297?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

### 部署artifacts 到tomcat

![](http://img.blog.csdn.net/20170922114348078?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

如果在Tomcat要部署多个artifact ，要注意 Application context 的路径不要有冲突。

如果以Debug模式启动，要热更新class和静态资源的话，要在Server中设置`On Update action` 和 `On frame deactivation` 为 `Update classes and resources`

![](http://img.blog.csdn.net/20170922114805746?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

## 启动Tomcat

![](http://img.blog.csdn.net/20170922114908836?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

两个按钮一个是正常启动，一个是调试启动。到目前为止就可以了。。。。。。

## 最后多说几句

在启动的时候可能遇到编译级别的问题。

`Error:(16, 61) java: '&lt;&gt;' operator is not allowed for source level below 1.7`

*   如果是Maven项目 需要在pom文件中指定项目的编译级别。编译的输出是按照pom构建项目的。**需要注意项目资源文件的拷贝**

```
&lt;build&gt;
       &lt;finalName&gt;test&lt;/finalName&gt;
       &lt;resources&gt;
           &lt;resource&gt;
               &lt;directory&gt;src/main/java&lt;/directory&gt;
               &lt;includes&gt;
                   &lt;include&gt;**/*.hbm.xml&lt;/include&gt;
               &lt;/includes&gt;
               &lt;filtering&gt;false&lt;/filtering&gt;
           &lt;/resource&gt;
           &lt;resource&gt;
               &lt;directory&gt;src/main/resources&lt;/directory&gt;
               &lt;includes&gt;
                   &lt;include&gt;**/*.xml&lt;/include&gt;
                   &lt;include&gt;**/*.properties&lt;/include&gt;
               &lt;/includes&gt;
           &lt;/resource&gt;
       &lt;/resources&gt;
       &lt;plugins&gt;
           &lt;plugin&gt;
               &lt;artifactId&gt;maven-war-plugin&lt;/artifactId&gt;
               &lt;version&gt;2.4&lt;/version&gt;
           &lt;/plugin&gt;
           &lt;plugin&gt;
               &lt;artifactId&gt;maven-compiler-plugin&lt;/artifactId&gt;
               &lt;configuration&gt;
                   &lt;source&gt;1.7&lt;/source&gt;
                   &lt;target&gt;1.7&lt;/target&gt;
               &lt;/configuration&gt;
           &lt;/plugin&gt;
       &lt;/plugins&gt;
&lt;/build&gt;
```

*   如果项目中既有jdk6 和 jdk7 就要添加多个jdk，（添加方法上文中有提到），还要更改项目的编译级别。

![](http://img.blog.csdn.net/20170922125404353?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

*   部署到Tomcat

还要更改Tomcat 的jdk版本， 如果部署的项目既用到jdk6 和jdk7 ，就要把Tomcat的jdk更改为7。

![](http://img.blog.csdn.net/20170922130057141?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvdTAxMzI5MTM2Nw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)
</pre>

**Comment by 88250** [comment]
我这里可以发布的：

![image](https://user-images.githubusercontent.com/873584/31710574-0033555c-b428-11e7-9e72-31630ec3f397.png)

----

我猜测可能是因为反向代理配置有问题，比如请求大小限制之类的。

**Comment by ZHI16** [comment]
如果Nginx配置有问题，那请求还会到项目中么？项目确实实时报错了。</br>
虽然没有解决，还是表示感谢。</br>
自己研究一下源码吧。

**Comment by 88250** [comment]
你发布一篇短一点的试试。我先关闭这个 issue 了，如果需要我帮忙，你艾特我就好。
