### ISSUE TITLE
服务长时间开启后后台无法登录

### ISSUE THREAD

**Issue by liyang0211** [b3log/solo#12377]
![image](https://user-images.githubusercontent.com/11283335/33531976-cfd711e2-d8cf-11e7-8d00-671b8126259b.png)

后台报错
``` 
[ERROR]-[2017-12-02 10:35:17]-[org.b3log.solo.processor.ArticleProcessor:1101]:
java.lang.NullPointerException
        at org.b3log.solo.repository.impl.ArticleRepositoryImpl.getNextArticle(ArticleRepositoryImpl.java:216)
        at org.b3log.solo.repository.impl.ArticleRepositoryImpl_$$_jvst2b4_3f._d16getNextArticle(ArticleRepositoryImpl_$$_jvst2b4_3f.java)
        at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
        at org.b3log.solo.repository.impl.ArticleRepositoryImpl_$$_jvst2b4_3f.getNextArticle(ArticleRepositoryImpl_$$_jvst2b4_3f.java)
        at org.b3log.solo.service.ArticleQueryService.getNextArticle(ArticleQueryService.java:911)
        at org.b3log.solo.service.ArticleQueryService_$$_jvst2b4_1e._d16getNextArticle(ArticleQueryService_$$_jvst2b4_1e.java)
        at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
        at org.b3log.solo.service.ArticleQueryService_$$_jvst2b4_1e.getNextArticle(ArticleQueryService_$$_jvst2b4_1e.java)
        at org.b3log.solo.processor.ArticleProcessor.prepareShowArticle(ArticleProcessor.java:1287)
        at org.b3log.solo.processor.ArticleProcessor.showArticle(ArticleProcessor.java:1078)
        at org.b3log.solo.processor.ArticleProcessor_$$_jvst2b4_f._d16showArticle(ArticleProcessor_$$_jvst2b4_f.java)
        at sun.reflect.GeneratedMethodAccessor120.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

```
04-Dec-2017 07:14:47.861 INFO [http-nio-80-exec-17] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:410)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

```

暂时org.b3log.solo.repository.impl.ArticleRepositoryImpl.getNextArticle(ArticleRepositoryImpl.java:216)加了非空验证，触发原因不明，但是已经发生了两次了

**Comment by liyang0211** [comment]
补充：登录一直loading，请求报了404

**Comment by 88250** [comment]
你用的是什么数据库？另外，发生 loading 的时候麻烦 F12 看下网络。

**Comment by liyang0211** [comment]
用的H2，登陆请求404

**Comment by 88250** [comment]
登录的时候有报错么？

**Comment by liyang0211** [comment]
没有直接报错，上面截的是最后报的两个错

**Comment by 88250** [comment]
理论上那里不会空的，因为是从数据库里面取的，方便的话你看下 article 表的 articleCreateDate 是否真的是空的。

登录 404 后台没有报错日志的话我估计是 NGINX 配置有点问题。

**Comment by liyang0211** [comment]
报空指针的不是createDate，应该是currentArticle
`final JSONObject currentArticle = get(articleId);`
通过无效ID去获取文章没有获取到

nginx不太熟，重启后没问题，过段时间就404，我再观察下，看是否是因为报错引起的

**Comment by 88250** [comment]
纳尼，当前文章不可能空才对。先不管了，多帮忙观察一下，先谢谢啦！

**Comment by liyang0211** [comment]
这里也开始报错
![image](https://user-images.githubusercontent.com/11283335/33584298-a0511d44-d999-11e7-99a2-93643693d5bb.png)

加了日志，日志级别也调成了trace，刚重启还没报错，不知道无效ID是从哪来的

**Comment by 88250** [comment]
好的，请帮忙看看。

**Comment by liyang0211** [comment]
又出现了，/login 报404，请求信息在这里，前面也没报错，看来跟那两个错是没有关系的
···
[DEBUG]-[2017-12-05 13:45:58]-[org.b3log.solo.SoloServletListener:126]: Request [
    method=OPTIONS,
    URL=http://liyangbest.com/login,
    contentType=null,
    characterEncoding=null,
    local=[
        addr=192.168.1.2,
        port=80,
        name=iZj6cgjb9m90kxrkn689hyZ],
    remote=[
        addr=122.128.109.12,
        port=9741,
        host=122.128.109.12],
    headers=[
        host=liyangbest.com
        access-control-request-method=POST
        origin=http://www.liyangbest.com
        user-agent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
        access-control-request-headers=content-type
        accept=*/*
        referer=http://www.liyangbest.com/login?goto=http%3A%2F%2Fliyangbest.com%2Fadmin-index.do%23main
        accept-encoding=gzip, deflate
        accept-language=zh-CN,zh;q=0.8
        connection=close
    ]
]
[DEBUG]-[2017-12-05 13:45:58]-[org.b3log.solo.SoloServletListener:191]: Gets a session[id=A5C60BC8FB38A8E9198E5D7550C42FA1, remoteAddr=122.128.109.12, User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36, isNew=true]
[DEBUG]-[2017-12-05 13:45:58]-[org.b3log.solo.service.StatisticMgmtService:413]: Current request [IP=122.128.109.12]
[DEBUG]-[2017-12-05 13:45:58]-[org.b3log.solo.service.StatisticMgmtService:416]: Current online visitor count [5]
[DEBUG]-[2017-12-05 13:45:58]-[org.b3log.solo.filter.PermalinkFilter:85]: Request URI[/login]
[DEBUG]-[2017-12-05 13:45:58]-[org.b3log.solo.filter.PermalinkFilter:91]: Skip filter request[URI=/login]
[TRACE]-[2017-12-05 13:45:58]-[org.b3log.solo.filter.InitCheckFilter:74]: Request[URI=/login]
[DEBUG]-[2017-12-05 13:45:58]-[org.b3log.solo.SoloServletListener:207]: Stopwatch:
[100]%, [2]ms [Request Initialized[requestURI=/login]]
···

**Comment by 88250** [comment]
整个是 OPTIONS 方法请求的，为啥浏览器要发 OPTIONS 请求呢，值得研究一下。
