### ISSUE TITLE
发布文章时报空指针[org.b3log.latke.servlet.renderer.JSONRenderer:153]: FreeMarker renders error

### ISSUE THREAD

**Issue by justin-wick** [b3log/solo#12499]
**Describe the bug 描述问题**
发布文章报空指针

**To Reproduce 重现步骤**
采用最新的solo-2.9.3.war ，启动方式 java -cp "WEB-INF/lib/*:WEB-INF/classes" org.b3log.solo.Starter -sp 80 -lp 80 -ssp 80
1. 登录管理后台
2. 点击发布文章
3. 复制http://www.jichujishu.com/articles/2018/08/02/1533176528492.html中的标题和内容
4. 后台显示处理中，然后一直没反应
5. 查看后台日志，发现如下错误
[ERROR]-[2018-09-06 16:07:21]-[org.b3log.latke.servlet.HttpControl:104]: Request [
    method=POST,
    URL=http://www.ofbizer.com/console/article/,
    contentType=application/x-www-form-urlencoded; charset=UTF-8,
    characterEncoding=UTF-8,
    local=[
        addr=104.207.144.60,
        port=80,
        name=104.207.144.60],
    remote=[
        addr=218.70.86.178,
        port=3374,
        host=218.70.86.178],
    headers=[
        Origin=http://www.ofbizer.com
        Cookie=JSESSIONID=1o7z6cvmivf2h1a9fkaywl2tpe; skin=; visited=%5B%22%2F%22%5D; solo=732e32b4c3cbba398e9012784ab5b73c25fd27ce9eb03f18b28ba42800d1d1865cb133b2f07320d0665b314506723762a500c63a502fd09c7f073d57fd3cb96c824b97a4b8f5821c90baecb1d04dd842a0a9135096cf6da709498b8914943ef4d7acbf24c78541c216d845891bd10a33d3d5122ba08b7e0bec2800637793584bd5446632c9eb88f14ffab2d5cd9bc841b37740c9614b8dc7dd8a6647d2dc74b2d9812c0e04160123bae60a6588c3adb4
        Accept=*/*
        X-Requested-With=XMLHttpRequest
        Connection=keep-alive
        User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
        Referer=http://www.ofbizer.com/admin-index.do
        Host=www.ofbizer.com
        Accept-Encoding=gzip, deflate
        Accept-Language=zh-CN,zh;q=0.9
        Content-Length=14052
        Content-Type=application/x-www-form-urlencoded; charset=UTF-8
    ]
] processing failed 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvokeHandler.java:58)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.java:108)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:60)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(RequestDispatchHandler.java:93)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestPrepareHandler.java:45)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:119)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:89)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:93)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.json.JSONException: JSONObject["article"] not found.
	at org.json.JSONObject.get(JSONObject.java:540)
	at org.json.JSONObject.getJSONObject(JSONObject.java:623)
	at org.b3log.solo.processor.console.ArticleConsole.addArticle(ArticleConsole.java:667)
	at org.b3log.solo.processor.console.ArticleConsole_$$_jvstd77_45._d0addArticle(ArticleConsole_$$_jvstd77_45.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
	at org.b3log.solo.processor.console.ArticleConsole_$$_jvstd77_45.addArticle(ArticleConsole_$$_jvstd77_45.java)
	... 43 more
[ERROR]-[2018-09-06 16:07:21]-[org.b3log.latke.servlet.renderer.JSONRenderer:153]: FreeMarker renders error
java.lang.NullPointerException
	at org.b3log.latke.servlet.renderer.JSONRenderer.render(JSONRenderer.java:141)
	at org.b3log.latke.servlet.DispatcherServlet.result(DispatcherServlet.java:111)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:89)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:93)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)

**Expected behavior 期待的结果**
文章成功发布。

**Screenshots 截屏或录像**
If applicable, add screenshots to help explain your problem. 如果可能，请尽量附加截图或录像来描述你遇到的问题。

**Desktop (please complete the following information): PC 端环境**
 - OS: centos x64
 - Browser 谷歌浏览器 
 - Version  68.0.3440.84（正式版本）

**Additional context 其他信息**
尝试过master 分支，报同样的错，可能是复制的文章内容导致

**Comment by 88250** [comment]
内容过长的话你看下容器或者反代的请求 body 大小的配置，可能是这个影响的。

**Comment by justin-wick** [comment]
目前用的是直接请求，域名直接解析，请求直接到机器的80端口
另外，刚测试的时候，即使内容较少也有这个问题

会不会是我机器配置有问题， 我用的服务器只有512M，1cpu

**Comment by 88250** [comment]
你是拉代码构建的么？

**Comment by justin-wick** [comment]
不是，直接用你们发布的，在百度云上的那个war包，使用的是内建的jetty发布方式

**Comment by 88250** [comment]
本地有问题么？

**Comment by 88250** [comment]
另外，你看下是不是用了代理，F12 看下请求状态。

**Comment by justin-wick** [comment]
没有开代理，本地测试很快，同样的文章

**Comment by justin-wick** [comment]
本地测试很快，没有开代理 可能是我服务器那边有问题

**Comment by 88250** [comment]
浏览器这端 F12 看下，服务器这端配置个 NGINX 反代，开 accesslog 方便定位。

**Comment by justin-wick** [comment]
应该是我服务器是国外的原因，我重新弄了一台腾讯云就完全好了，谢谢。
