### ISSUE TITLE
init时报Initialize Solo error异常

### ISSUE THREAD

**Issue by tuser4198** [b3log/solo#12498]
**Describe the bug 描述问题**
本地（系统mac 10.13.6）idea启动后，在localhost:8080页面中输入完邮箱，用户名，密码后，点击init，报如下错误：
[INFO ]-[2018-09-05 15:41:10]-[org.b3log.solo.Starter:151]: Standalone mode, see https://github.com/b3log/solo/issues/12037 for more details.
[INFO ]-[2018-09-05 15:41:12]-[org.b3log.solo.SoloServletListener:211]: Please open browser and visit [http://localhost:8080] to init your Solo, and then enjoy it :-p
[INFO ]-[2018-09-05 15:41:12]-[org.b3log.solo.SoloServletListener:130]: Solo is running [http://localhost:8080]
[INFO ]-[2018-09-05 15:42:02]-[org.b3log.solo.service.InitService:204]: YOUR DATA will be stored in directory [jdbc:h2:/Users/jacky/solo_h2/db], please pay more attention to it~
[ERROR]-[2018-09-05 15:42:02]-[org.b3log.latke.Latkes:862]: Read skin configuration error[msg=null]
[WARN ]-[2018-09-05 15:42:02]-[org.b3log.solo.service.InitService:240]: Retrying to init Solo[retries=2]
[ERROR]-[2018-09-05 15:42:02]-[org.b3log.latke.Latkes:862]: Read skin configuration error[msg=null]
[WARN ]-[2018-09-05 15:42:02]-[org.b3log.solo.service.InitService:240]: Retrying to init Solo[retries=1]
[ERROR]-[2018-09-05 15:42:02]-[org.b3log.latke.Latkes:862]: Read skin configuration error[msg=null]
[WARN ]-[2018-09-05 15:42:02]-[org.b3log.solo.service.InitService:240]: Retrying to init Solo[retries=0]
[ERROR]-[2018-09-05 15:42:02]-[org.b3log.latke.Latkes:862]: Read skin configuration error[msg=null]
[ERROR]-[2018-09-05 15:42:02]-[org.b3log.solo.service.InitService:234]: Initialize Solo error
org.b3log.latke.repository.RepositoryException: A json object to persist to repository[name=b3_solo_option] does not contain a key[optionValue]
	at org.b3log.latke.repository.Repositories.check(Repositories.java:193)
	at org.b3log.latke.repository.AbstractRepository.add(AbstractRepository.java:107)
	at org.b3log.solo.repository.impl.OptionRepositoryImpl_$$_jvste3f_9._d0add(OptionRepositoryImpl_$$_jvste3f_9.java)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
	at org.b3log.solo.repository.impl.OptionRepositoryImpl_$$_jvste3f_9.add(OptionRepositoryImpl_$$_jvste3f_9.java)
	at org.b3log.solo.service.InitService.initPreference(InitService.java:786)
	at org.b3log.solo.service.InitService.init(InitService.java:223)
	at org.b3log.solo.service.InitService_$$_jvste3f_4b._d6init(InitService_$$_jvste3f_4b.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
	at org.b3log.solo.service.InitService_$$_jvste3f_4b.init(InitService_$$_jvste3f_4b.java)
	at org.b3log.solo.processor.InitProcessor.initSolo(InitProcessor.java:172)
	at org.b3log.solo.processor.InitProcessor_$$_jvste3f_33._d5initSolo(InitProcessor_$$_jvste3f_33.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
	at org.b3log.solo.processor.InitProcessor_$$_jvste3f_33.initSolo(InitProcessor_$$_jvste3f_33.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvokeHandler.java:58)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.java:108)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:60)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(RequestDispatchHandler.java:93)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestPrepareHandler.java:45)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:119)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:96)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:93)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
[ERROR]-[2018-09-05 15:42:02]-[org.b3log.solo.processor.InitProcessor:186]: Initailize Solo error: A json object to persist to repository[name=b3_solo_option] does not contain a key[optionValue]
org.b3log.latke.service.ServiceException: Initailize Solo error: A json object to persist to repository[name=b3_solo_option] does not contain a key[optionValue]
	at org.b3log.solo.service.InitService.init(InitService.java:235)
	at org.b3log.solo.service.InitService_$$_jvste3f_4b._d6init(InitService_$$_jvste3f_4b.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
	at org.b3log.solo.service.InitService_$$_jvste3f_4b.init(InitService_$$_jvste3f_4b.java)
	at org.b3log.solo.processor.InitProcessor.initSolo(InitProcessor.java:172)
	at org.b3log.solo.processor.InitProcessor_$$_jvste3f_33._d5initSolo(InitProcessor_$$_jvste3f_33.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.bean.JavassistMethodHandler.invoke(JavassistMethodHandler.java:106)
	at org.b3log.solo.processor.InitProcessor_$$_jvste3f_33.initSolo(InitProcessor_$$_jvste3f_33.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.servlet.handler.MethodInvokeHandler.handle(MethodInvokeHandler.java:58)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.AdviceHandler.handle(AdviceHandler.java:108)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.ArgsHandler.handle(ArgsHandler.java:60)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.RequestDispatchHandler.handle(RequestDispatchHandler.java:93)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.RequestPrepareHandler.handle(RequestPrepareHandler.java:45)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:119)
	at org.b3log.latke.servlet.HttpControl.nextHandler(HttpControl.java:99)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:96)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:93)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
**To Reproduce 重现步骤**
Steps to reproduce the behavior: 请描述如何重现这个问题：
1. clone solo github项目，本地（系统mac 10.13.6） idea启动Starter。
2. 打开localhost:8080，输入用户名，密码，邮箱点击 init，报错。

**Expected behavior 期待的结果**
个人本意时搭建个个人网站，所以希望能正常使用网站。

**Screenshots 截屏或录像**
![image](https://user-images.githubusercontent.com/6936064/45079135-4d61e380-b124-11e8-9396-1334ebd6d7bb.png)

**Desktop (please complete the following information): PC 端环境**
 - OS: mac 10.13.6
 - Browser chrome 68.0.3440.106（正式版本） （64 位）

**Comment by 88250** [comment]
克隆代码的时候请参考文档 https://hacpai.com/article/1493822943172
