### ISSUE TITLE
20190925下载的master分支皮肤ease在solo-2.9.4中多个页面无法正常渲染,显示500页面

### ISSUE THREAD

**Issue by 1102568869** [b3log/solo#12528]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 描述问题
20190925下载的master分支皮肤ease在solo-2.9.4中无法正常渲染,显示500页面

### 重现步骤

请描述如何重现这个问题：

solo从2.9.3升级而来,20190925下载的master分支皮肤ease在solo-2.9.4中无法正常渲染,显示500页面

### 期待的结果

正常显示博客首页以及进行其他操作

### 截屏或录像

![image](https://user-images.githubusercontent.com/13030698/46011222-caff8a80-c0f7-11e8-967e-9a7962abeb3b.png)

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

```
[ERROR]-[2018-09-25 19:16:30]-[org.b3log.latke.servlet.renderer.freemarker.AbstractFreeMarkerRenderer:138]: FreeMarker renders error
FreeMarker template error:
An error has occurred when reading existing sub-variable "articleUpdateDate"; see cause exception! The type of the containing value was: extended_hash+string (org.json.JSONObject wrapped into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${article.articleUpdateDate?string("y...  [in template "article-list.ftl" at line 44, column 13]
	- Reached through: #include "article-list.ftl"  [in template "index.ftl" at line 39, column 21]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:183)
	at freemarker.core.Dot._eval(Dot.java:43)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.BuiltInsForMultipleTypes$stringBI._eval(BuiltInsForMultipleTypes.java:692)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.MethodCall._eval(MethodCall.java:58)
	at freemarker.core.Expression.eval(Expression.java:83)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
	at freemarker.core.Environment.visit(Environment.java:330)
	at freemarker.core.Environment.visit(Environment.java:372)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:317)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:242)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:642)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:107)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:93)
	at freemarker.core.Environment.visit(Environment.java:330)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.include(Environment.java:2582)
	at freemarker.core.Include.accept(Include.java:171)
	at freemarker.core.Environment.visit(Environment.java:330)
	at freemarker.core.Environment.visit(Environment.java:336)
	at freemarker.core.Environment.process(Environment.java:309)
	at freemarker.template.Template.process(Template.java:384)
	at org.b3log.latke.servlet.renderer.freemarker.AbstractFreeMarkerRenderer.genHTML(AbstractFreeMarkerRenderer.java:162)
	at org.b3log.solo.processor.renderer.SkinRenderer.genHTML(SkinRenderer.java:75)
	at org.b3log.latke.servlet.renderer.freemarker.AbstractFreeMarkerRenderer.render(AbstractFreeMarkerRenderer.java:133)
	at org.b3log.latke.servlet.DispatcherServlet.result(DispatcherServlet.java:111)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
	at freemarker.ext.beans.BeanModel.invokeGenericGet(BeanModel.java:272)
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:152)
	... 60 more
Caused by: org.json.JSONException: JSONObject["articleUpdateDate"] not found.
	at org.json.JSONObject.get(JSONObject.java:540)
	... 66 more

```

**Comment by 88250** [comment]
请参考 https://hacpai.com/article/1537694179006 获取源码部分。

**Comment by 1102568869** [comment]
> 请参考 https://hacpai.com/article/1537694179006 获取源码部分。

唔,我是使用的自行下载skin部分放进skins目录的方式,替换ease主题之后,并不是所有的页面均500,我先使用别的主题(能正常使用的)将页面切换到tags/links/article详情页等页面,然后切换回ease主题,刷新页面,能正常访问,看起来只有`#include article-list.ftl`的页面受到影响...

**Comment by 88250** [comment]
https://github.com/b3log/solo-skins 这个库上是最新的，应该没问题才对。
