### ISSUE TITLE
启动时加载插件报NPE

### ISSUE THREAD

**Issue by linkerlin** [b3log/solo#12563]
最新的master代码，linux环境。
WARN ]-[2018-11-02 02:05:21]-[org.b3log.latke.plugin.PluginManager:148]: Load plugin under directory[/plugins/symphony-interest/] failed
java.lang.NullPointerException
        at java.base/java.util.ArrayDeque.addLast(ArrayDeque.java:304)
        at java.base/java.util.ArrayDeque.add(ArrayDeque.java:495)
        at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:145)
        at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:162)
        at java.base/java.net.URLClassLoader.<init>(URLClassLoader.java:120)
        at org.b3log.latke.plugin.PluginManager.load(PluginManager.java:185)
        at org.b3log.latke.plugin.PluginManager.load(PluginManager.java:142)
        at org.b3log.latke.plugin.PluginManager.getPlugins(PluginManager.java:112)
        at org.b3log.latke.plugin.ViewLoadEventHandler.action(ViewLoadEventHandler.java:55)

**Comment by 88250** [comment]
我在 Linux 环境试了下没能重现，如果还有更多信息麻烦提供，谢谢。

**Comment by 88250** [comment]
我先关闭了，有问题再看。
