### ISSUE TITLE
邮件发送依赖库补全

### ISSUE THREAD

**Issue by kevinBobo** [b3log/solo#12606]
我在配置了邮件配置之后发现邮件无法发送，异常如下

```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com/sun/mail/util/FolderClosedIOException
	at org.b3log.solo.mail.local.MailSender.convert2JavaMailMsg(MailSender.java:111)
	at org.b3log.solo.mail.local.MailSender.sendMail(MailSender.java:155)
	at org.b3log.solo.mail.local.LocalMailService.lambda$send$0(LocalMailService.java:37)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.sun.mail.util.FolderClosedIOException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more
```

我在本地调试之后，发现是依赖的缺失引起的，希望更正重新发布一个版本
我在本地加入一下依赖之后功能正常

```xml
<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>javax.mail</artifactId>
    <version>${javax.mail.version}</version>
</dependency>
```

**Comment by 88250** [comment]
感谢反馈，下个版本我们会确认一下问题并修复。
