### ISSUE TITLE
docker 打包后，无法显示plugin

### ISSUE THREAD

**Issue by Rechardone** [b3log/solo#12621]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 描述问题
mac环境下，docker-compose 打出的包没有插件，一直报错，
Load plugin under directory[/plugins/symphony-interest/] failed
java.lang.NullPointerException
at java.base/java.util.ArrayDeque.addLast(ArrayDeque.java:304)
at java.base/java.util.ArrayDeque.add(ArrayDeque.java:495)
at java.base/jdk.internal.loader.URLClassPath.(URLClassPath.java:145)
at java.base/jdk.internal.loader.URLClassPath.(URLClassPath.java:162)
at java.base/java.net.URLClassLoader.(URLClassLoader.java:120)
at org.b3log.latke.plugin.PluginManager.load(PluginManager.java:185)
at org.b3log.latke.plugin.PluginManager.load(PluginManager.java:142)
at org.b3log.latke.plugin.PluginManager.getPlugins(PluginManager.java:112)
at org.b3log.latke.plugin.ViewLoadEventHandler.action(ViewLoadEventHandler.java:55)

之后我在mac下，
mvn install -DskipTests -Pci && mv target/solo/* /opt/b3log/solo/
java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter
启动也还是没有插件

### 重现步骤
在mac上solo目录中执行 mvn install -DskipTests -Pci && mv target/solo/* /opt/b3log/solo/
java -cp WEB-INF/lib/*:WEB-INF/classes org.b3log.solo.Starter

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

![image](https://user-images.githubusercontent.com/20181214/51087128-f03d0500-1789-11e9-93d5-c843b2d64491.png)

### 桌面端环境

- OS: [mac 10.14.2 (18C54)]
- Browser [chrome 71.0.3578.98]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
我们先确认一下，这个和 docker 应该没关系吧？

**Comment by 88250** [comment]
我刚刚在 mac 上试了下，重现不了哦。还有问题请跟帖，issue 我关闭了。

**Comment by Trumeet** [comment]
同（
