### ISSUE TITLE
从v2.9.9 升级到v3发生的问题

### ISSUE THREAD

**Issue by kevinBobo** [b3log/solo#12655]
我之前是v2.9.9 是我自己手动打的包
在升级v3的时候无法登录后台
报空指针的异常
然后我以为找不到用户 把数据库用户删了想让他重新注册
发现没有
我又下载了官方的包
现在
异常如下
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.service.DataModelService_$$_jvst2b9_40.setArticlesExProperties(DataModelService_$$_jvst2b9_40.java)
        at org.b3log.solo.service.DataModelService.fillIndexArticles(DataModelService.java:215)
        ... 67 more
Caused by: java.lang.NullPointerException
        at org.b3log.solo.service.DataModelService.setArticleExProperties(DataModelService.java:892)
        ... 76 more
[WARN ]-[2019-02-19 10:32:34]-[com.zaxxer.hikari.pool.ProxyLeakTask:84]: Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@2d0399f4 on thread pool-2-thread-1, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
        at org.b3log.latke.repository.jdbc.util.Connections.getConnection(Connections.java:190)
        at org.b3log.latke.repository.jdbc.JdbcRepository.getConnection(JdbcRepository.java:799)
        at org.b3log.latke.repository.jdbc.JdbcRepository.get(JdbcRepository.java:470)
        at org.b3log.latke.repository.AbstractRepository.get(AbstractRepository.java:149)
        at org.b3log.solo.repository.UserRepository.getAdmin(UserRepository.java:149)
        at org.b3log.solo.repository.UserRepository_$$_jvst2b9_27._d10getAdmin(UserRepository_$$_jvst2b9_27.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.repository.UserRepository_$$_jvst2b9_27.getAdmin(UserRepository_$$_jvst2b9_27.java)
        at org.b3log.solo.service.UserQueryService.getAdmin(UserQueryService.java:93)
        at org.b3log.solo.service.UserQueryService_$$_jvst2b9_16._d3getAdmin(UserQueryService_$$_jvst2b9_16.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.service.UserQueryService_$$_jvst2b9_16.getAdmin(UserQueryService_$$_jvst2b9_16.java)
        at org.b3log.solo.service.PageMgmtService.refreshGitHub(PageMgmtService.java:136)
        at org.b3log.solo.service.PageMgmtService_$$_jvst2b9_f._d10refreshGitHub(PageMgmtService_$$_jvst2b9_f.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.service.PageMgmtService_$$_jvst2b9_f.refreshGitHub(PageMgmtService_$$_jvst2b9_f.java)
        at org.b3log.solo.service.CronMgmtService.lambda$start$1(CronMgmtService.java:93)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

如何重新注册一下用户呢?

**Comment by 88250** [comment]
这就有点麻烦了，删了的话关联性被破坏了。如果只是删了这个用户（user 表的一行的话）可以恢复一下，用户 id 用 article 表里面的。

**Comment by kevinBobo** [comment]
只删了用户一行,其他字段呢

**Comment by 88250** [comment]
@kevinBobo 

* 邮箱、用户名填 GitHub 的
* userURL 随便填一个地址就行，密码也随便填个（现在是用授权登录，这个字段暂时没用了）
* userRole 如果是管理员就填 `adminRole`，其他角色：`visitorRole`（访客，没有后台权限），`defaultRole`（普通用户，可以登录后台写文章）
* userAvatar 填个可外链的头像图片地址
* userB3Key 填社区这边设置的
* userGitHubId 留空

你先这样恢复，看看能否不报错访问。

**Comment by kevinBobo** [comment]
谢啦 我弄了个空数据库新注册了一下,然后复制过去了,目前正常了,看来之前最早可能是我打的dev包的问题
