### ISSUE TITLE
用户管理页面加载不进去

### ISSUE THREAD

**Issue by TerickJojo** [b3log/solo#12654]
下面是报错
```
[ERROR]-[2019-02-19 04:09:56]-[org.b3log.latke.servlet.renderer.AbstractFreeMarkerRenderer:131]: Renders template [admin/admin-user-list.ftl] failed [Request [
    method=GET,
    URL=http://www.lklovetlx.com/admin-user-list.do,
    contentType=null,
    characterEncoding=UTF-8,
    local=[
        addr=172.18.116.180,
        port=80,
        name=172.18.116.180],
    remote=[
        addr=73.231.211.122,
        port=38513,
        host=73.231.211.122],
    headers=[
        Cookie=visited=%5B%22%2F%22%5D; skin=tree-house; solo=cfd2be4469b13ec2a772eb0f8fc7332af87bc2e751c2b7fee2b2f6dca1dd891e7206af899ac4d3983161c9808c1a847c38ab39b8f647052fbd2d6b7a91ad7039
        Accept=text/html, */*; q=0.01
        X-Requested-With=XMLHttpRequest
        Connection=keep-alive
        User-Agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
        Referer=http://www.lklovetlx.com/admin-index.do
        Host=www.lklovetlx.com
        Accept-Encoding=gzip, deflate
        Accept-Language=en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
    ]
]]
FreeMarker template error:
The following has evaluated to null or missing:
==> commentEmail1Label  [in template "admin/admin-user-list.ftl" at line 29, column 36]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${commentEmail1Label}  [in template "admin/admin-user-list.ftl" at line 29, column 34]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:467)
...
...
...
```
麻烦了

**Comment by 88250** [comment]
请重新下载发布包应该能解决问题，辛苦了。

https://github.com/b3log/solo/issues/12649

**Comment by TerickJojo** [comment]
谢谢了

**Comment by TerickJojo** [comment]
> 请重新下载发布包应该能解决问题，辛苦了。
> 
> #12649

解决了，下载war包，提取最新admin-user-list.ftl覆盖老的admin-user-list.ftl，搞定。
不过还是要谢谢了

**Comment by 88250** [comment]
还有其他问题的话欢迎随时反馈，感谢 ❤️

**Comment by CodingOX** [comment]
... 刚想反馈！
