### ISSUE TITLE
GitHub登录失败

### ISSUE THREAD

**Issue by vitalQ** [b3log/solo#12662]
### 描述问题

登录失败,GitHub授权后自动跳回登录页,通过war直接部署,版本3.0.0

### 错误日志

`[INFO ]-[2019-02-21 05:16:09]-[org.b3log.solo.processor.OAuthGitHubProcessor:229]: Logged in [email=, remoteAddr=127.0.0.1] with GitHub oauth
[ERROR]-[2019-02-21 05:16:35]-[org.b3log.latke.repository.jdbc.JdbcRepository:153]: Add failed
java.sql.SQLException: Incorrect string value: '\xE4\xB8\x80\xE6\xAC\xBE...' for column 'optionValue' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:975)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:392)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.b3log.latke.repository.jdbc.util.JdbcUtil.executeSql(JdbcUtil.java:91)
        at org.b3log.latke.repository.jdbc.JdbcRepository.add(JdbcRepository.java:150)
        at org.b3log.latke.repository.AbstractRepository.add(AbstractRepository.java:100)
        at org.b3log.solo.service.InitService.initPreference(InitService.java:510)
        at org.b3log.solo.service.InitService.init(InitService.java:219)
        at org.b3log.solo.service.InitService_$$_jvst323_25._d6init(InitService_$$_jvst323_25.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.service.InitService_$$_jvst323_25.init(InitService_$$_jvst323_25.java)
        at org.b3log.solo.processor.OAuthGitHubProcessor.showGitHubCallback(OAuthGitHubProcessor.java:196)
        at org.b3log.solo.processor.OAuthGitHubProcessor_$$_jvst323_17._d8showGitHubCallback(OAuthGitHubProcessor_$$_jvst323_17.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.processor.OAuthGitHubProcessor_$$_jvst323_17.showGitHubCallback(OAuthGitHubProcessor_$$_jvst323_17.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.servlet.handler.ContextHandleHandler.handle(ContextHandleHandler.java:45)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
        at org.b3log.latke.servlet.handler.BeforeHandleHandler.handle(BeforeHandleHandler.java:81)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
        at org.b3log.latke.servlet.handler.RouteHandler.handle(RouteHandler.java:202)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
        at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:118)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
        at org.b3log.latke.servlet.DispatcherServlet.handle(DispatcherServlet.java:87)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:84)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:92)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
[WARN ]-[2019-02-21 05:16:35]-[org.b3log.solo.util.Solos:340]: Can not write cookie
java.lang.NullPointerException
        at org.b3log.solo.util.Solos.login(Solos.java:327)
        at org.b3log.solo.processor.OAuthGitHubProcessor.showGitHubCallback(OAuthGitHubProcessor.java:227)
        at org.b3log.solo.processor.OAuthGitHubProcessor_$$_jvst323_17._d8showGitHubCallback(OAuthGitHubProcessor_$$_jvst323_17.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.processor.OAuthGitHubProcessor_$$_jvst323_17.showGitHubCallback(OAuthGitHubProcessor_$$_jvst323_17.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.servlet.handler.ContextHandleHandler.handle(ContextHandleHandler.java:45)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
        at org.b3log.latke.servlet.handler.BeforeHandleHandler.handle(BeforeHandleHandler.java:81)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
        at org.b3log.latke.servlet.handler.RouteHandler.handle(RouteHandler.java:202)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
        at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:118)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
        at org.b3log.latke.servlet.DispatcherServlet.handle(DispatcherServlet.java:87)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:84)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:92)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:64)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:491)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
[INFO ]-[2019-02-21 05:16:36]-[org.b3log.solo.processor.OAuthGitHubProcessor:229]: Logged in [email=, remoteAddr=127.0.0.1] with GitHub oauth
`

### 期待的结果

应该正常登录

### 其他信息

GitHub用户名和黑客派都是vitalq

**Comment by 88250** [comment]
你好，创建数据库的时候要用 utf8mb4 字符集。
