### ISSUE TITLE
JDK11 插件加载报错

### ISSUE THREAD

**Issue by MrLaibin** [b3log/solo#12672]
### 描述问题
docker logs 出现 Load plugin under directory[/plugins/symphony-interest/] failed
java.lang.NullPointerException
         at java.base/java.util.ArrayDeque.addLast(ArrayDeque.java:304)
	at java.base/java.util.ArrayDeque.add(ArrayDeque.java:495)
	at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:154)
	at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:171)
	at java.base/java.net.URLClassLoader.<init>(URLClassLoader.java:120)
	at org.b3log.latke.plugin.PluginManager.load(PluginManager.java:185)
	at org.b3log.latke.plugin.PluginManager.load(PluginManager.java:142)
	at org.b3log.latke.plugin.PluginManager.getPlugins(PluginManager.java:112)
	at org.b3log.latke.plugin.ViewLoadEventHandler.action(ViewLoadEventHandler.java:55)
	at org.b3log.latke.event.AbstractEventListener.performAction(AbstractEventListener.java:54)
	at org.b3log.latke.event.AbstractEventQueue.notifyListeners(AbstractEventQueue.java:142)
	at org.b3log.latke.event.SynchronizedEventQueue.fireEvent(SynchronizedEventQueue.java:66)
	at org.b3log.latke.event.EventManager.fireEventSynchronously(EventManager.java:44)
	at org.b3log.solo.service.DataModelService.fillBlogFooter(DataModelService.java:621)
	at org.b3log.solo.service.DataModelService.fillCommon(DataModelService.java:552)
	at org.b3log.solo.service.DataModelService_$$_jvst667_57._d4fillCommon(DataModelService_$$_jvst667_57.java)
	at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.service.DataModelService_$$_jvst667_57.fillCommon(DataModelService_$$_jvst667_57.java)
	at org.b3log.solo.processor.IndexProcessor.showIndex(IndexProcessor.java:131)
	at org.b3log.solo.processor.IndexProcessor_$$_jvst667_20._d7showIndex(IndexProcessor_$$_jvst667_20.java)
	at jdk.internal.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.processor.IndexProcessor_$$_jvst667_20.showIndex(IndexProcessor_$$_jvst667_20.java)
	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.b3log.latke.servlet.handler.ContextHandleHandler.handle(ContextHandleHandler.java:45)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
	at org.b3log.latke.servlet.handler.BeforeHandleHandler.handle(BeforeHandleHandler.java:81)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
	at org.b3log.latke.servlet.handler.RouteHandler.handle(RouteHandler.java:202)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:118)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:471)
	at org.b3log.latke.servlet.DispatcherServlet.handle(DispatcherServlet.java:87)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.b3log.solo.filter.PermalinkFilter.doFilter(PermalinkFilter.java:84)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.b3log.solo.filter.InitCheckFilter.doFilter(InitCheckFilter.java:85)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.b3log.latke.servlet.filter.EncodingFilter.doFilter(EncodingFilter.java:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)

### 重现步骤
使用docker volume create solo_datas && docker run --privileged --name solo --restart=unless-stopped -p 8080:8080 -v solo_datas:/opt/b3log/backup/ -d 88250/solo 启动项目，过了半个月出现这个提示

**Comment by laibinCN** [comment]
version 2.99

**Comment by 88250** [comment]
麻烦升级到 v3，如果还能重现这个问题请 reopen。

**Comment by Willh92** [comment]
一样的问题，环境是tomcat-9.0  版本3.1.0
Load plugin under directory[/plugins/list/] failed
java.lang.NullPointerException
        at java.base/java.util.ArrayDeque.addLast(ArrayDeque.java:304)
        at java.base/java.util.ArrayDeque.add(ArrayDeque.java:495)
        at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:154)
        at java.base/jdk.internal.loader.URLClassPath.<init>(URLClassPath.java:171)
        at java.base/java.net.URLClassLoader.<init>(URLClassLoader.java:120)
        at org.b3log.latke.plugin.PluginManager.load(PluginManager.java:185)
        at org.b3log.latke.plugin.PluginManager.load(PluginManager.java:142)
        at org.b3log.latke.plugin.PluginManager.getPlugins(PluginManager.java:112)
        at org.b3log.latke.plugin.ViewLoadEventHandler.action(ViewLoadEventHandler.java:55)
        at org.b3log.latke.event.AbstractEventListener.performAction(AbstractEventListener.java:54)
        at org.b3log.latke.event.AbstractEventQueue.notifyListeners(AbstractEventQueue.java:142)
        at org.b3log.latke.event.SynchronizedEventQueue.fireEvent(SynchronizedEventQueue.java:66)
        at org.b3log.latke.event.EventManager.fireEventSynchronously(EventManager.java:44)
        at org.b3log.solo.service.DataModelService.fillBlogFooter(DataModelService.java:633)
        at org.b3log.solo.service.DataModelService.fillCommon(DataModelService.java:564)
        at org.b3log.solo.service.DataModelService_$$_jvsta90_4b._d5fillCommon(DataModelService_$$_jvsta90_4b.java)
        at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.service.DataModelService_$$_jvsta90_4b.fillCommon(DataModelService_$$_jvsta90_4b.java)
        at org.b3log.solo.processor.ArticleProcessor.showArticle(ArticleProcessor.java:758)
        at org.b3log.solo.processor.ArticleProcessor_$$_jvsta90_15._d17showArticle(ArticleProcessor_$$_jvsta90_15.java)
        at jdk.internal.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.processor.ArticleProcessor_$$_jvsta90_15.showArticle(ArticleProcessor_$$_jvsta90_15.java)
        at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.b3log.latke.servlet.handler.ContextHandleHandler.handle(ContextHandleHandler.java:45)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:544)
        at org.b3log.latke.servlet.handler.BeforeHandleHandler.handle(BeforeHandleHandler.java:81)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:544)
        at org.b3log.latke.servlet.handler.RouteHandler.handle(RouteHandler.java:202)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:544)
        at org.b3log.solo.processor.PermalinkHandler.handle(PermalinkHandler.java:118)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:544)
        at org.b3log.solo.processor.InitCheckHandler.handle(InitCheckHandler.java:67)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:544)
        at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:118)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:544)
        at org.b3log.latke.servlet.DispatcherServlet.handle(DispatcherServlet.java:96)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by 88250** [comment]
@Willh92 麻烦说一下详细的部署步骤，谢谢。

**Comment by Willh92** [comment]
centos 下 tomcat-9.0.13  jdk:11.0.1 用的mysql
主要latke配置: serverScheme=https  serverHost=willh.cn  serverPort=
试过自己打的war包，跟下载的，覆盖旧版配置文件后，释放到webapps下。
原因是发现文章目录没了，才去看的日志，台发现报插件加载失败，后发现查看后台插件列表是空的。

**Comment by 88250** [comment]
部署后容器自动解压后有 plugins 目录吗？

![image](https://user-images.githubusercontent.com/873584/53694967-56402300-3df0-11e9-9ad5-c3459931a3d8.png)

**Comment by Willh92** [comment]
有的
![default](https://user-images.githubusercontent.com/11692730/53695004-10d02580-3df1-11e9-98f6-1b1cc502c100.PNG)

**Comment by 88250** [comment]
这就有点奇怪了，我这边刚刚试了 ROOT 下也是可以的，不过我是在 Windows 上测试的，Tomcat 9.0.12。
这样，你那边如果容器下只有这一个 Java Web 应用的话，可以考虑使用独立模式部署。

**Comment by Willh92** [comment]
我再排查试试看，因为以前版本是正常的。升级了好几个版本，没注意到从哪个版本开始出的问题。

**Comment by 88250** [comment]
@Willh92 辛苦了 😓

**Comment by Willh92** [comment]
jdk环境的问题，降到1.8就正常了

**Comment by 88250** [comment]
@Willh92 等后续我会做下 JDK 的兼容性测试和更新，非常感谢帮忙测试和指出问题。

**Comment by Willh92** [comment]
@88250 辛苦了

**Comment by dulinanaaa** [comment]
@88250 我也同样遇到了问题，之前让用jdk和tomcat比较新的，于是用了tomcat9和jdk11。发现插件加载失败。在这里遇到了同样问题，降了jdk版本，改成jdk10后，windows和linux的就都可以了

**Comment by 88250** [comment]
@dulinanaaa 感谢帮忙测试反馈，后续我们尽量改改看，先暂时用低版本 JDK。

**Comment by 88250** [comment]
Docker 部署方式已通过降低基础镜像 JDK 版本修复，程序方面暂时不做调整。
