### ISSUE TITLE
log4j 默认日志配置不输出文件

### ISSUE THREAD

**Issue by jianhong-li** [b3log/solo#12747]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/solo)搜寻资料解决问题。

----

### 描述问题

当使用 tomcat容器时,默认的log4j 的日志文件:solo.log,其配置为:
````
log4j.appender.file.File=solo.log
````
文件位置:`log4j.properties`,此配置会在 tomcat 的启动命令运行位置作为当前目录.
比如我在`/home/solo/`目录启动.
我的 web 的目录为:`/home/x/www/solo-web`我的 solo web 的目录如下:
````
cache
conf
logs
temp
webapps
work
````
此时启动 tomcat 容器时.如果在如上:`/home/solo/`目录重启 tomcat.则 solo.log 会创建在此目录下:`/home/solo/solo.log`如果此目录没有权限则会出错:

### 重现步骤

在其它目录启动 tomcat. 会报:
````
31-Mar-2019 20:31:33.365 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: solo.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:66)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.b3log.latke.logging.Logger.<init>(Logger.java:50)
[root@iZ25a8x4jw7Z /home/q/www/solo-web/logs]#
````

### 期待的结果

正确记录日志

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。
### 桌面端环境
- OS:  CentOS release 6.8 (Final)

**Comment by jianhong-li** [comment]
建议添加环境变量.如:
log4j.appender.file.File=${catalina.base}/logs/solo.log

**Comment by 88250** [comment]
@jianhong-li 有个问题是不用 Tomcat 的话没有这个环境变量。这样，下个版本改为默认不启用文件输出。
