### ISSUE TITLE
solo 3.6.1 升级 3.6.2 数据库报错

### ISSUE THREAD

**Issue by lizhongyue248** [b3log/solo#12797]
### 描述问题

solo 3.6.1 升级 3.6.2 数据库报错，信息如下

```
[INFO ]-[2019-06-08 17:26:28]-[com.zaxxer.hikari.HikariDataSource:110]: HikariPool-1 - Starting...
[INFO ]-[2019-06-08 17:26:28]-[com.zaxxer.hikari.HikariDataSource:123]: HikariPool-1 - Start completed.
[INFO ]-[2019-06-08 17:26:28]-[org.b3log.solo.upgrade.V361_362:59]: Upgrading from version [3.6.1] to version [3.6.2]....
[ERROR]-[2019-06-08 17:26:29]-[org.b3log.latke.repository.jdbc.JdbcRepository:261]: Update failed
java.sql.SQLException: Incorrect string value: '\xF0\x9F\x98\x82 \xF0...' for column 'commentContent' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:975)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:392)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.b3log.latke.repository.jdbc.util.JdbcUtil.executeSql(JdbcUtil.java:91)
        at org.b3log.latke.repository.jdbc.JdbcRepository.update(JdbcRepository.java:259)
        at org.b3log.latke.repository.AbstractRepository.update(AbstractRepository.java:111)
        at org.b3log.solo.repository.CommentRepository.update(CommentRepository.java:93)
        at org.b3log.solo.repository.CommentRepository_$$_jvst13d_4c._d31update(CommentRepository_$$_jvst13d_4c.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.repository.CommentRepository_$$_jvst13d_4c.update(CommentRepository_$$_jvst13d_4c.java)
        at org.b3log.solo.upgrade.V361_362.perform(V361_362.java:83)
        at org.b3log.solo.service.UpgradeService.upgrade(UpgradeService.java:83)
        at org.b3log.solo.service.UpgradeService_$$_jvst13d_2a._d8upgrade(UpgradeService_$$_jvst13d_2a.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.service.UpgradeService_$$_jvst13d_2a.upgrade(UpgradeService_$$_jvst13d_2a.java)
        at org.b3log.solo.SoloServletListener.contextInitialized(SoloServletListener.java:111)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:952)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:917)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)

```

### 截屏或录像

![](https://resources.echocow.cn/file/2019/05/26/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20190608173633.png)

### 期望的解决方式

在不重启 mysql 的情况下解决此问题

**Comment by 88250** [comment]
这个问题是以前版本初始化生成表的时候有缺陷，后来在 v3 修复过。

现在需要麻烦你自己手动更新一下 comment 表的 commentContent 字段字符集为 utf8mb4，排序规则用 utf8mb4_general_ci，另外 article 表的 articleAbstract、articleContent、articleAbstractText 这三个字段也请手动更新一下，辛苦了。

**Comment by lizhongyue248** [comment]
使用 
```
alter table blog_echo_comment modify commentContent text character SET utf8mb4 COLLATE utf8mb4_general_ci;
```
修改，没有作用，使用 `SHOW FULL COLUMNS FROM blog_echo_comment;` 查看字符集
```
+----------------------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+-----------------------------------------------------------------+
| Field                      | Type         | Collation          | Null | Key | Default | Extra | Privileges                      | Comment                                                         |
+----------------------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+-----------------------------------------------------------------+
| oId                        | varchar(19)  | utf8_general_ci    | NO   | PRI | NULL    |       | select,insert,update,references | 主键                                                            |
| commentContent             | text         | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |                                                                 |
| commentCreated             | bigint(20)   | NULL               | NO   |     | NULL    |       | select,insert,update,references | 评论时间戳                                                      |
| commentName                | varchar(50)  | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论人名称                                                      |
| commentOnId                | varchar(19)  | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论的文章/页面的 id                                            |
| commentSharpURL            | varchar(255) | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论访问路径，带 # 锚点                                         |
| commentThumbnailURL        | text         | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论人头像图片链接地址                                          |
| commentURL                 | varchar(255) | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论人链接地址                                                  |
| commentOriginalCommentId   | varchar(19)  | utf8_general_ci    | YES  |     | NULL    |       | select,insert,update,references | 评论回复时原始的评论 id，即父评论 id                            |
| commentOriginalCommentName | varchar(50)  | utf8_general_ci    | YES  |     | NULL    |       | select,insert,update,references | 评论回复时原始的评论人名称，即父评论人名称                      |
+----------------------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+-----------------------------------------------------------------+
```
似乎是对的啊

**Comment by lizhongyue248** [comment]
使用 `alter table blog_echo_comment modify commentContent text character SET utf8mb4 COLLATE utf8mb4_general_ci;`  进行修改然后重启，无效，错误相同。

使用 `SHOW FULL COLUMNS FROM blog_echo_comment;` 进行查看
```
mysql> SHOW FULL COLUMNS FROM blog_echo_comment;
+----------------------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+-----------------------------------------------------------------+
| Field                      | Type         | Collation          | Null | Key | Default | Extra | Privileges                      | Comment                                                         |
+----------------------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+-----------------------------------------------------------------+
| oId                        | varchar(19)  | utf8_general_ci    | NO   | PRI | NULL    |       | select,insert,update,references | 主键                                                            |
| commentContent             | text         | utf8mb4_general_ci | YES  |     | NULL    |       | select,insert,update,references |                                                                 |
| commentCreated             | bigint(20)   | NULL               | NO   |     | NULL    |       | select,insert,update,references | 评论时间戳                                                      |
| commentName                | varchar(50)  | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论人名称                                                      |
| commentOnId                | varchar(19)  | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论的文章/页面的 id                                            |
| commentSharpURL            | varchar(255) | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论访问路径，带 # 锚点                                         |
| commentThumbnailURL        | text         | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论人头像图片链接地址                                          |
| commentURL                 | varchar(255) | utf8_general_ci    | NO   |     | NULL    |       | select,insert,update,references | 评论人链接地址                                                  |
| commentOriginalCommentId   | varchar(19)  | utf8_general_ci    | YES  |     | NULL    |       | select,insert,update,references | 评论回复时原始的评论 id，即父评论 id                            |
| commentOriginalCommentName | varchar(50)  | utf8_general_ci    | YES  |     | NULL    |       | select,insert,update,references | 评论回复时原始的评论人名称，即父评论人名称                      |
+----------------------------+--------------+--------------------+------+-----+---------+-------+---------------------------------+-----------------------------------------------------------------+
10 rows in set (0.00 sec)

```
是对的啊

**Comment by 88250** [comment]
请问 MySQL 的版本是多少？我猜测可能是驱动不太匹配版本。

**Comment by lizhongyue248** [comment]
`Server version: 5.7.21 MySQL`

**Comment by 88250** [comment]
那真有可能是因为数据库驱动兼容性的问题，降级一下试试看？

**Comment by lizhongyue248** [comment]
噗噗噗，那我是不是得自己下载下来master分支然后自己构建打包再弄上去？=-=

**Comment by 88250** [comment]
要不升级一下数据库吧，这样简单些。5.7 升级 8 没什么问题，我这里 3 个环境都升级过了。

**Comment by lizhongyue248** [comment]
不太现实=-= 六个应用跑着的，都用着 mysql 的，有些用的驱动不支持 mysql 8。。。

以后版本都只能用 mysql 8 吗？

**Comment by 88250** [comment]
目前你是通过手动还是脚本部署的？可以把 MySQL connector jar 换成 5.7 的，然后配置文件中的连接串也更新为 5.7 的。

**Comment by lizhongyue248** [comment]
目前是脚本自动部署的。但是我看 3.6.1 和 3.6.2 的 jar 包都是  mysql-connector-java-8.0.12.jar 啊，那么应该不会是 jar 包的问题吧

**Comment by lizhongyue248** [comment]
在 3.6.1 下是正常使用的。

**Comment by 88250** [comment]
因为之前数据库中没有直接存 emoji 原生字符，而是转成了别名 ASCII `:smile:` 存，所以没有问题。v3.6.2 做了一个更新，就是将回帖内容中的 ASCII 表情专为原生 Unicode 存储。

**Comment by lizhongyue248** [comment]
那我尝试降级 jar 包试一试。

**Comment by 88250** [comment]
https://github.com/b3log/solo/issues/12798

**Comment by 88250** [comment]
v3.6.2 的 war 已经更新 https://github.com/b3log/solo/releases

**Comment by lizhongyue248** [comment]
已经解决，十分感谢！
