### ISSUE TITLE
tomcat 换成docker 3.6.1升级3.6.3失败

### ISSUE THREAD

**Issue by aeneag** [b3log/solo#12815]
[INFO ]-[2019-07-16 15:55:15]-[org.b3log.solo.util.Markdowns:135]: [markdown-http] is not available, uses built-in [flexmark] for markdown processing. Please read FAQ section in user guide (https://hacpai.com/article/1492881378588) for more details.
[INFO ]-[2019-07-16 15:55:15]-[org.b3log.solo.SoloServletListener:99]: Solo is booting [ver=3.6.3, servletContainer=jetty/9.4.12.v20180830, os=Linux, isDocker=true, markdownHttpAvailable=false, pid=1, runtimeDatabase=MYSQL, runtimeMode=PRODUCTION, jdbc.username=root, jdbc.URL=jdbc:mysql://localhost:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC]
[INFO ]-[2019-07-16 15:55:15]-[com.zaxxer.hikari.HikariDataSource:110]: HikariPool-1 - Starting...
[INFO ]-[2019-07-16 15:55:16]-[com.zaxxer.hikari.HikariDataSource:123]: HikariPool-1 - Start completed.
[INFO ]-[2019-07-16 15:55:16]-[org.b3log.solo.upgrade.V361_362:59]: Upgrading from version [3.6.1] to version [3.6.2]....
[ERROR]-[2019-07-16 15:55:16]-[org.b3log.latke.repository.jdbc.JdbcRepository:261]: Update failed
java.sql.SQLException: Incorrect string value: '\xF0\x9F\x98\x84  ' for column 'commentContent' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:372)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.b3log.latke.repository.jdbc.util.JdbcUtil.executeSql(JdbcUtil.java:91)
	at org.b3log.latke.repository.jdbc.JdbcRepository.update(JdbcRepository.java:259)
	at org.b3log.latke.repository.AbstractRepository.update(AbstractRepository.java:111)
	at org.b3log.solo.repository.CommentRepository.update(CommentRepository.java:93)
	at org.b3log.solo.repository.CommentRepository_$$_jvst36c_1a._d31update(CommentRepository_$$_jvst36c_1a.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.repository.CommentRepository_$$_jvst36c_1a.update(CommentRepository_$$_jvst36c_1a.java)
	at org.b3log.solo.upgrade.V361_362.perform(V361_362.java:83)
	at org.b3log.solo.service.UpgradeService.upgrade(UpgradeService.java:85)
	at org.b3log.solo.service.UpgradeService_$$_jvst36c_a._d8upgrade(UpgradeService_$$_jvst36c_a.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.service.UpgradeService_$$_jvst36c_a.upgrade(UpgradeService_$$_jvst36c_a.java)
	at org.b3log.solo.SoloServletListener.contextInitialized(SoloServletListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:952)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:917)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:416)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:383)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.b3log.solo.Starter.main(Starter.java:177)
[ERROR]-[2019-07-16 15:55:16]-[org.b3log.solo.upgrade.V361_362:92]: Upgrade failed!
org.b3log.latke.repository.RepositoryException: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x98\x84  ' for column 'commentContent' at row 1
	at org.b3log.latke.repository.jdbc.JdbcRepository.update(JdbcRepository.java:263)
	at org.b3log.latke.repository.AbstractRepository.update(AbstractRepository.java:111)
	at org.b3log.solo.repository.CommentRepository.update(CommentRepository.java:93)
	at org.b3log.solo.repository.CommentRepository_$$_jvst36c_1a._d31update(CommentRepository_$$_jvst36c_1a.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.repository.CommentRepository_$$_jvst36c_1a.update(CommentRepository_$$_jvst36c_1a.java)
	at org.b3log.solo.upgrade.V361_362.perform(V361_362.java:83)
	at org.b3log.solo.service.UpgradeService.upgrade(UpgradeService.java:85)
	at org.b3log.solo.service.UpgradeService_$$_jvst36c_a._d8upgrade(UpgradeService_$$_jvst36c_a.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.service.UpgradeService_$$_jvst36c_a.upgrade(UpgradeService_$$_jvst36c_a.java)
	at org.b3log.solo.SoloServletListener.contextInitialized(SoloServletListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:952)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:917)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:416)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:383)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.b3log.solo.Starter.main(Starter.java:177)
Caused by: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x98\x84  ' for column 'commentContent' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:372)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.b3log.latke.repository.jdbc.util.JdbcUtil.executeSql(JdbcUtil.java:91)
	at org.b3log.latke.repository.jdbc.JdbcRepository.update(JdbcRepository.java:259)
	... 36 more
[ERROR]-[2019-07-16 15:55:16]-[org.b3log.solo.service.UpgradeService:95]: Upgrade failed, please contact the Solo developers or reports this issue: https://github.com/b3log/solo/issues/new
java.lang.Exception: Upgrade failed from version [3.6.1] to version [3.6.2]
	at org.b3log.solo.upgrade.V361_362.perform(V361_362.java:94)
	at org.b3log.solo.service.UpgradeService.upgrade(UpgradeService.java:85)
	at org.b3log.solo.service.UpgradeService_$$_jvst36c_a._d8upgrade(UpgradeService_$$_jvst36c_a.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.service.UpgradeService_$$_jvst36c_a.upgrade(UpgradeService_$$_jvst36c_a.java)
	at org.b3log.solo.SoloServletListener.contextInitialized(SoloServletListener.java:111)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:952)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:917)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:847)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:416)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:383)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.b3log.solo.Starter.main(Starter.java:177)

**Comment by aeneag** [comment]
错误已经找到，手动更新一下 comment 表的 commentContent 字段字符集为 utf8mb4，排序规则用 utf8mb4_general_ci，另外 article 表的 articleAbstract、articleContent、articleAbstractText 这三个字段也手动更新一下，这样即可解决
