### ISSUE TITLE
博客文章编辑：内容渲染出现了一些问题

### ISSUE THREAD

**Issue by zhangchensong** [b3log/solo#12841]
博客文章编辑过程中预览框提示：内容渲染出现了一些问题
[http://zhangchensong.top:8080/articles/2019/07/26/1564156188337.html](url)
![QQ图片20190727001837](https://user-images.githubusercontent.com/37106292/61966226-bc7a4c00-b004-11e9-8ec4-c2c17aaf8161.png)
文章内容中包含一些SQL注入代码
# solo.log : 
```
[ERROR]-[2019-07-27 00:32:37]-[org.b3log.solo.util.Markdowns:234]: Markdown failed [md=POST '.......................博文内容.....................']
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.b3log.solo.util.Markdowns.toHTML(Markdowns.java:220)
        at org.b3log.solo.service.ArticleQueryService.markdown(ArticleQueryService.java:949)
        at org.b3log.solo.service.ArticleQueryService_$$_jvst148_33._d23markdown(ArticleQueryService_$$_jvst148_33.java)
        at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.service.ArticleQueryService_$$_jvst148_33.markdown(ArticleQueryService_$$_jvst148_33.java)
        at org.b3log.solo.processor.ArticleProcessor.showArticle(ArticleProcessor.java:725)
        at org.b3log.solo.processor.ArticleProcessor_$$_jvst148_3d._d17showArticle(ArticleProcessor_$$_jvst148_3d.java)
        at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
        at org.b3log.solo.processor.ArticleProcessor_$$_jvst148_3d.showArticle(ArticleProcessor_$$_jvst148_3d.java)
        at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.b3log.latke.servlet.handler.ContextHandleHandler.handle(ContextHandleHandler.java:45)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:545)
        at org.b3log.latke.servlet.handler.BeforeHandleHandler.handle(BeforeHandleHandler.java:81)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:545)
        at org.b3log.latke.servlet.handler.RouteHandler.handle(RouteHandler.java:202)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:545)
        at org.b3log.solo.processor.PermalinkHandler.handle(PermalinkHandler.java:118)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:545)
        at org.b3log.solo.processor.InitCheckHandler.handle(InitCheckHandler.java:67)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:545)
        at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:118)
        at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:545)
        at org.b3log.latke.servlet.DispatcherServlet.handle(DispatcherServlet.java:96)
        at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
```

**Comment by 88250** [comment]
如果方便的话请 zip 上传一下文章文本以方便我进行重现。

另外，代码块请用 Markdown 语法进行排版。建议使用 ` ``` ` 进行包裹，具体用法请参考 [Markdown 教程](https://hacpai.com/guide/markdown)。

**Comment by zhangchensong** [comment]
@88250 
[sql.zip](https://github.com/b3log/solo/files/3437808/sql.zip)
但是同步到hacpai社区的文章正常显示

**Comment by 88250** [comment]
收到，稍后进行排查。Markdown 渲染是个有点复杂的过程，不排除是 Solo 内置的 Markdown 引擎（flexmark）存在问题。你可以先尝试使用 [markdown-http](https://github.com/b3log/markdown-http) 来进行渲染效果增强，说不定这个问题就解决了。

**Comment by zhangchensong** [comment]
@88250 
我定位到了错误位置，文章内容的一个表格中含有字符`||`
* 如果不使用"\`"和"\`"包裹字符`||`，其中一个`|`会被认为是markdown语法中表格的组成部分
* 如果使用"\`"符号包裹`||`，会出现渲染错误的问题

**Comment by 88250** [comment]
感谢帮忙定位，我会尽量尝试修复。

**Comment by 88250** [comment]
我把你上传的文本进行了测试，暂时没有发现问题哦。我这里本地渲染是 OK 的，先关闭这个 issue 了。如果有进一步细节信息麻烦告诉我。

另外，如果方便的话请在 v3.6.4 发布后（预计 8 月份会发布这个版本）进行升级，如果还能重现问题麻烦重新打开这个 issue，谢谢。
