### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by superstonne** [b3log/solo#12918]

**Comment by 88250** [comment]
请提供相关信息。

**Comment by superstonne** [comment]
阿里云香港地区的服务器，管理员也无法登录。

[ERROR]-[2019-10-09 18:05:55]-[org.b3log.solo.util.GitHubs:71]: Gets GitHub repos failed
jodd.http.HttpException: Can't connect to: https://hacpai.com/github/repos?id=7440390; <--- java.net.SocketTimeoutException: connect timed out
	at jodd.http.HttpRequest.open(HttpRequest.java:755)
	at jodd.http.HttpRequest.open(HttpRequest.java:737)
	at jodd.http.HttpRequest._send(HttpRequest.java:859)
	at jodd.http.HttpRequest.send(HttpRequest.java:831)
	at org.b3log.solo.util.GitHubs.getGitHubRepos(GitHubs.java:57)
	at org.b3log.solo.service.ArticleMgmtService.refreshGitHub(ArticleMgmtService.java:194)
	at org.b3log.solo.service.ArticleMgmtService_$$_jvstecc_1e._d12refreshGitHub(ArticleMgmtService_$$_jvstecc_1e.java)
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.service.ArticleMgmtService_$$_jvstecc_1e.refreshGitHub(ArticleMgmtService_$$_jvstecc_1e.java)
	at org.b3log.solo.service.CronMgmtService.lambda$start$1(CronMgmtService.java:99)

**Comment by 88250** [comment]
麻烦提供一下 IP 地址（为了安全可以隐藏最后一段），我看下社区服务器日志。

**Comment by superstonne** [comment]
47.52.232.***

**Comment by 88250** [comment]
社区服务器上没有这个 IP 的相关日志，我估计可能是你的服务器网络到社区服务器网络不通吧。社区服务器目前是阿里云杭州节点。

可以打开浏览器 F12 网络看下整个登录过程的请求。

**Comment by superstonne** [comment]
[root@iZj6cadzdewrn6qxixsmlxZ ~]# ping hacpai.com
PING hacpai.com (118.31.188.179) 56(84) bytes of data.
^C
--- hacpai.com ping statistics ---
33 packets transmitted, 0 received, 100% packet loss, time 31999ms

[root@iZj6cadzdewrn6qxixsmlxZ ~]#


服务器上无法 ping 通这个域名，感觉阿里云服务器出问题。

**Comment by 88250** [comment]
社区服务器的网络应该没有问题 http://ping.chinaz.com/hacpai.com
可能是你那边服务器的网络有问题哦，阿里云香港节点最近因为某事可能不稳也正常 😂 

这个问题我先关闭了，有任何需要请直接跟帖。
