### ISSUE TITLE
归档页面 404

### ISSUE THREAD

**Issue by panjf2000** [b3log/solo#12940]
### 描述问题
在归档页面点击任意一个月，404

### 重现步骤

请描述如何重现这个问题：
1. 进入归档页
2. 点击任意一个月的文章，404

### 期待的结果

bug fix

### 截屏或录像

![image](https://user-images.githubusercontent.com/7496278/68545624-c3896680-0409-11ea-9633-7c925b4247bf.png)

### 桌面端环境

- OS: mac
- Browser: chrome
- Version: 78.0.3904.97

### 其他信息
```
[ERROR]-[2019-11-10 22:21:51]-[org.b3log.solo.service.ArticleQueryService:664]: Gets articles by archive date [id=1573293321129] failed
org.b3log.latke.repository.RepositoryException: java.sql.SQLSyntaxErrorException: Expression #20 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'solo.aa.oId' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
	at org.b3log.latke.repository.jdbc.JdbcRepository.select(JdbcRepository.java:482)
	at org.b3log.latke.repository.AbstractRepository.select(AbstractRepository.java:154)
	at org.b3log.solo.service.ArticleQueryService.getArticlesByArchiveDate(ArticleQueryService.java:654)
	at org.b3log.solo.service.ArticleQueryService_$$_jvst2b8_1c._d8getArticlesByArchiveDate(ArticleQueryService_$$_jvst2b8_1c.java)
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.service.ArticleQueryService_$$_jvst2b8_1c.getArticlesByArchiveDate(ArticleQueryService_$$_jvst2b8_1c.java)
	at org.b3log.solo.processor.ArticleProcessor.showArchiveArticles(ArticleProcessor.java:669)
	at org.b3log.solo.processor.ArticleProcessor_$$_jvst2b8_41._d16showArchiveArticles(ArticleProcessor_$$_jvst2b8_41.java)
	at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.processor.ArticleProcessor_$$_jvst2b8_41.showArchiveArticles(ArticleProcessor_$$_jvst2b8_41.java)
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.servlet.handler.ContextHandleHandler.handle(ContextHandleHandler.java:45)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.handler.BeforeHandleHandler.handle(BeforeHandleHandler.java:81)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.handler.RouteHandler.handle(RouteHandler.java:203)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.solo.processor.PermalinkHandler.handle(PermalinkHandler.java:79)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.solo.processor.InitCheckHandler.handle(InitCheckHandler.java:67)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:118)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.DispatcherServlet.handle(DispatcherServlet.java:96)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: Expression #20 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'solo.aa.oId' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.b3log.latke.repository.jdbc.util.JdbcUtil.queryJson(JdbcUtil.java:159)
	at org.b3log.latke.repository.jdbc.util.JdbcUtil.queryJsonArray(JdbcUtil.java:130)
	at org.b3log.latke.repository.jdbc.JdbcRepository.select(JdbcRepository.java:475)
	... 63 more
[ERROR]-[2019-11-10 22:21:51]-[org.b3log.solo.processor.ArticleProcessor:688]: org.b3log.latke.repository.RepositoryException: java.sql.SQLSyntaxErrorException: Expression #20 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'solo.aa.oId' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
org.b3log.latke.service.ServiceException: org.b3log.latke.repository.RepositoryException: java.sql.SQLSyntaxErrorException: Expression #20 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'solo.aa.oId' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
	at org.b3log.solo.service.ArticleQueryService.getArticlesByArchiveDate(ArticleQueryService.java:665)
	at org.b3log.solo.service.ArticleQueryService_$$_jvst2b8_1c._d8getArticlesByArchiveDate(ArticleQueryService_$$_jvst2b8_1c.java)
	at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.service.ArticleQueryService_$$_jvst2b8_1c.getArticlesByArchiveDate(ArticleQueryService_$$_jvst2b8_1c.java)
	at org.b3log.solo.processor.ArticleProcessor.showArchiveArticles(ArticleProcessor.java:669)
	at org.b3log.solo.processor.ArticleProcessor_$$_jvst2b8_41._d16showArchiveArticles(ArticleProcessor_$$_jvst2b8_41.java)
	at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.ioc.JavassistMethodHandler.invoke(JavassistMethodHandler.java:116)
	at org.b3log.solo.processor.ArticleProcessor_$$_jvst2b8_41.showArchiveArticles(ArticleProcessor_$$_jvst2b8_41.java)
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.b3log.latke.servlet.handler.ContextHandleHandler.handle(ContextHandleHandler.java:45)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.handler.BeforeHandleHandler.handle(BeforeHandleHandler.java:81)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.handler.RouteHandler.handle(RouteHandler.java:203)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.solo.processor.PermalinkHandler.handle(PermalinkHandler.java:79)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.solo.processor.InitCheckHandler.handle(InitCheckHandler.java:67)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.handler.StaticResourceHandler.handle(StaticResourceHandler.java:118)
	at org.b3log.latke.servlet.RequestContext.handle(RequestContext.java:546)
	at org.b3log.latke.servlet.DispatcherServlet.handle(DispatcherServlet.java:96)
	at org.b3log.latke.servlet.DispatcherServlet.service(DispatcherServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.b3log.latke.repository.RepositoryException: java.sql.SQLSyntaxErrorException: Expression #20 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'solo.aa.oId' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
	at org.b3log.latke.repository.jdbc.JdbcRepository.select(JdbcRepository.java:482)
	at org.b3log.latke.repository.AbstractRepository.select(AbstractRepository.java:154)
	at org.b3log.solo.service.ArticleQueryService.getArticlesByArchiveDate(ArticleQueryService.java:654)
	... 61 more
Caused by: java.sql.SQLSyntaxErrorException: Expression #20 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'solo.aa.oId' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.b3log.latke.repository.jdbc.util.JdbcUtil.queryJson(JdbcUtil.java:159)
	at org.b3log.latke.repository.jdbc.util.JdbcUtil.queryJsonArray(JdbcUtil.java:130)
	at org.b3log.latke.repository.jdbc.JdbcRepository.select(JdbcRepository.java:475)
	... 63 more
```

**Comment by 88250** [comment]
v3.6.7 会进行修复，感谢反馈。
